@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户
participant 商户
participant 支付平台
participant 第三方渠道


用户 -> 商户: 请求支付
商户 -> 支付平台: 请求支付
支付平台 -> 支付平台: 鉴权、风控、幂等、落数据、渠道路由
支付平台 -> 第三方渠道: 请求支付
第三方渠道 -> 支付平台:返回
支付平台 -> 商户: 返回
商户 -> 用户: 返回
用户 -> 用户: 确认支付
支付平台 -> 第三方渠道: 没有收到支付消息，查询支付结果
第三方渠道 -> 支付平台: 返回支付结果
第三方渠道 --> 支付平台: 支付消息
支付平台 -> 支付平台: 验签、加密
商户 -> 支付平台: 查询支付结果
支付平台 -> 商户: 返回支付结果
支付平台 --> 商户: 支付消息、重试机制
@enduml